version: '3.7'

services:

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - "${DEV_CLIENT_PORT}:3000"
    depends_on:
      - node
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    env_file:
      - dev-client.env
  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/src/app'
    ports:
      - "${DEV_SERVER_PORT}:8080"
    depends_on:
      - mongo
    env_file:
      - dev-server.env
  mongo:
    image: mongo
    ports:
      - "${DEV_DB_PORT}:27017"
