version: '3.7'

services:

  react:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - "${DEV_CLIENT_PORT}:3000"
    depends_on:
      - node
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  node:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - './server:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "${DEV_SERVER_PORT}:8080"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - DEV_CLIENT_PORT=${DEV_CLIENT_PORT}
      - DB_URI=${DEV_DB_URI}
  mongo:
    image: mongo
    ports:
      - "${DEV_DB_PORT}:27017"
