version: '3.7'

services:

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - node
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/src/app'
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"