version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true