// @reducer: items
export const ITEMS_UPDATE_ALL_SUCCESS = 'ITEMS_UPDATE_ALL_SUCCESS';
export const ITEMS_UPDATE_ALL_FAILURE = 'ITEMS_UPDATE_ALL_FAILURE';
export const ITEMS_UPDATE_INPUT_CONTENTS = 'ITEMS_UPDATE_INPUT_CONTENTS';
export const ITEMS_SUBMIT_ITEM_SUCCESS = 'ITEMS_SUBMIT_ITEM_SUCCESS';
export const ITEMS_SUBMIT_ITEM_FAILURE = 'ITEMS_SUBMIT_ITEM_FAILURE';
export const ITEMS_DELETE_ITEM_SUCCESS = 'ITEMS_DELETE_ITEM_SUCCESS';
export const ITEMS_DELETE_ITEM_FAILURE = 'ITEMS_DELETE_ITEM_FAILURE';