export const UPDATE_ALL_SUCCESS = 'UPDATE_ALL_SUCCESS';
export const UPDATE_ALL_FAILURE = 'UPDATE_ALL_FAILURE';
export const UPDATE_INPUT_CONTENTS = 'UPDATE_INPUT_CONTENTS';
export const SUBMIT_ITEM_SUCCESS = 'SUBMIT_ITEM_SUCCESS';
export const SUBMIT_ITEM_FAILURE = 'SUBMIT_ITEM_FAILURE';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';